package com.customresumegen.app;

import java.util.ArrayList;
import java.util.List;

public class ColorData {

    public static List<ColorItem> getAllColors() {
        List<ColorItem> colors = new ArrayList<>();

        colors.add(new ColorItem("Black", "#000000"));
        colors.add(new ColorItem("Black Blue", "#040720"));
        colors.add(new ColorItem("Night", "#0C090A"));
        colors.add(new ColorItem("Charcoal", "#34282C"));
        colors.add(new ColorItem("Oil", "#3B3131"));
        colors.add(new ColorItem("Stormy Gray", "#3A3B3C"));
        colors.add(new ColorItem("Light Black", "#454545"));
        colors.add(new ColorItem("Dark Steampunk", "#4D4D4F"));
        colors.add(new ColorItem("Black Cat", "#413839"));
        colors.add(new ColorItem("Iridium", "#3D3C3A"));
        colors.add(new ColorItem("Black Eel", "#463E3F"));
        colors.add(new ColorItem("Black Cow", "#4C4646"));
        colors.add(new ColorItem("Gray Wolf", "#504A4B"));
        colors.add(new ColorItem("Vampire Gray", "#565051"));
        colors.add(new ColorItem("Iron Gray", "#52595D"));
        colors.add(new ColorItem("Gray Dolphin", "#5C5858"));
        colors.add(new ColorItem("Carbon Gray", "#625D5D"));
        colors.add(new ColorItem("Ash Gray", "#666362"));
        colors.add(new ColorItem("DimGray or DimGrey", "#696969"));
        colors.add(new ColorItem("Nardo Gray", "#686A6C"));
        colors.add(new ColorItem("Cloudy Gray", "#6D6968"));
        colors.add(new ColorItem("Smokey Gray", "#726E6D"));
        colors.add(new ColorItem("Alien Gray", "#736F6E"));
        colors.add(new ColorItem("Sonic Silver", "#757575"));
        colors.add(new ColorItem("Platinum Gray", "#797979"));
        colors.add(new ColorItem("Granite", "#837E7C"));
        colors.add(new ColorItem("Gray or Grey", "#808080"));
        colors.add(new ColorItem("Battleship Gray", "#848482"));
        colors.add(new ColorItem("Sheet Metal", "#888B90"));
        colors.add(new ColorItem("Dark Gainsboro", "#8C8C8C"));
        colors.add(new ColorItem("Gunmetal Gray", "#8D918D"));
        colors.add(new ColorItem("Cold Metal", "#9B9A96"));
        colors.add(new ColorItem("Stainless Steel Gray", "#99A3A3"));
        colors.add(new ColorItem("DarkGray or DarkGrey", "#A9A9A9"));
        colors.add(new ColorItem("Chrome Aluminum", "#A8A9AD"));
        colors.add(new ColorItem("Gray Cloud", "#B6B6B4"));
        colors.add(new ColorItem("Metal", "#B6B6B6"));
        colors.add(new ColorItem("Silver", "#C0C0C0"));
        colors.add(new ColorItem("Steampunk", "#C9C1C1"));
        colors.add(new ColorItem("Pale Silver", "#C9C0BB"));
        colors.add(new ColorItem("Gear Steel Gray", "#C0C6C7"));
        colors.add(new ColorItem("Gray Goose", "#D1D0CE"));
        colors.add(new ColorItem("Platinum Silver", "#CECECE"));
        colors.add(new ColorItem("LightGray or LightGrey", "#D3D3D3"));
        colors.add(new ColorItem("Silver White", "#DADBDD"));
        colors.add(new ColorItem("Gainsboro", "#DCDCDC"));
        colors.add(new ColorItem("Light Steel Gray", "#E0E5E5"));
        colors.add(new ColorItem("WhiteSmoke", "#F5F5F5"));
        colors.add(new ColorItem("White Gray", "#EEEEEE"));
        colors.add(new ColorItem("Platinum", "#E5E4E2"));
        colors.add(new ColorItem("Metallic Silver", "#BCC6CC"));
        colors.add(new ColorItem("Blue Gray", "#98AFC7"));
        colors.add(new ColorItem("Roman Silver", "#838996"));
        colors.add(new ColorItem("LightSlateGray or LightSlateGrey", "#778899"));
        colors.add(new ColorItem("SlateGray or SlateGrey", "#708090"));
        colors.add(new ColorItem("Rat Gray", "#6D7B8D"));
        colors.add(new ColorItem("Slate Granite Gray", "#657383"));
        colors.add(new ColorItem("Jet Gray", "#616D7E"));
        colors.add(new ColorItem("Mist Blue", "#646D7E"));
        colors.add(new ColorItem("Steel Gray", "#71797E"));
        colors.add(new ColorItem("Marble Blue", "#566D7E"));
        colors.add(new ColorItem("Slate Blue Gray", "#737CA1"));
        colors.add(new ColorItem("Light Purple Blue", "#728FCE"));
        colors.add(new ColorItem("Azure Blue", "#4863A0"));
        colors.add(new ColorItem("Estoril Blue", "#2F539B"));
        colors.add(new ColorItem("Blue Jay", "#2B547E"));
        colors.add(new ColorItem("Charcoal Blue", "#36454F"));
        colors.add(new ColorItem("Dark Blue Gray", "#29465B"));
        colors.add(new ColorItem("Dark Slate", "#2B3856"));
        colors.add(new ColorItem("Deep Sea Blue", "#123456"));
        colors.add(new ColorItem("Night Blue", "#151B54"));
        colors.add(new ColorItem("MidnightBlue", "#191970"));
        colors.add(new ColorItem("Navy", "#000080"));
        colors.add(new ColorItem("Denim Dark Blue", "#151B8D"));
        colors.add(new ColorItem("DarkBlue", "#00008B"));
        colors.add(new ColorItem("Lapis Blue", "#15317E"));
        colors.add(new ColorItem("New Midnight Blue", "#0000A0"));
        colors.add(new ColorItem("Earth Blue", "#0000A5"));
        colors.add(new ColorItem("Cobalt Blue", "#0020C2"));
        colors.add(new ColorItem("MediumBlue", "#0000CD"));
        colors.add(new ColorItem("Blueberry Blue", "#0041C2"));
        colors.add(new ColorItem("Canary Blue", "#2916F5"));
        colors.add(new ColorItem("Blue", "#0000FF"));
        colors.add(new ColorItem("Samco Blue", "#0002FF"));
        colors.add(new ColorItem("Bright Blue", "#0909FF"));
        colors.add(new ColorItem("Blue Orchid", "#1F45FC"));
        colors.add(new ColorItem("Sapphire Blue", "#2554C7"));
        colors.add(new ColorItem("Blue Eyes", "#1569C7"));
        colors.add(new ColorItem("Bright Navy Blue", "#1974D2"));
        colors.add(new ColorItem("Balloon Blue", "#2B60DE"));
        colors.add(new ColorItem("RoyalBlue", "#4169E1"));
        colors.add(new ColorItem("Ocean Blue", "#2B65EC"));
        colors.add(new ColorItem("Dark Sky Blue", "#0059FF"));
        colors.add(new ColorItem("Blue Ribbon", "#306EFF"));
        colors.add(new ColorItem("Blue Dress", "#157DEC"));
        colors.add(new ColorItem("Neon Blue", "#1589FF"));
        colors.add(new ColorItem("DodgerBlue", "#1E90FF"));
        colors.add(new ColorItem("Water Blue", "#0E87CC"));
        colors.add(new ColorItem("Glacial Blue Ice", "#368BC1"));
        colors.add(new ColorItem("SteelBlue", "#4682B4"));
        colors.add(new ColorItem("Silk Blue", "#488AC7"));
        colors.add(new ColorItem("Windows Blue", "#357EC7"));
        colors.add(new ColorItem("Blue Ivy", "#3090C7"));
        colors.add(new ColorItem("Cyan Blue", "#14A3C7"));
        colors.add(new ColorItem("Blue Koi", "#659EC7"));
        colors.add(new ColorItem("Columbia Blue", "#87AFC7"));
        colors.add(new ColorItem("Baby Blue", "#95B9C7"));
        colors.add(new ColorItem("CornflowerBlue", "#6495ED"));
        colors.add(new ColorItem("Sky Blue Dress", "#6698FF"));
        colors.add(new ColorItem("Iceberg", "#56A5EC"));
        colors.add(new ColorItem("Butterfly Blue", "#38ACEC"));
        colors.add(new ColorItem("DeepSkyBlue", "#00BFFF"));
        colors.add(new ColorItem("Midday Blue", "#3BB9FF"));
        colors.add(new ColorItem("Crystal Blue", "#5CB3FF"));
        colors.add(new ColorItem("Denim Blue", "#79BAEC"));
        colors.add(new ColorItem("Day Sky Blue", "#82CAFF"));
        colors.add(new ColorItem("LightSkyBlue", "#87CEFA"));
        colors.add(new ColorItem("SkyBlue", "#87CEEB"));
        colors.add(new ColorItem("Jeans Blue", "#A0CFEC"));
        colors.add(new ColorItem("Blue Angel", "#B7CEEC"));
        colors.add(new ColorItem("Pastel Blue", "#B4CFEC"));
        colors.add(new ColorItem("Light Day Blue", "#ADDFFF"));
        colors.add(new ColorItem("Sea Blue", "#C2DFFF"));
        colors.add(new ColorItem("Heavenly Blue", "#C6DEFF"));
        colors.add(new ColorItem("Robin Egg Blue", "#BDEDFF"));
        colors.add(new ColorItem("PowderBlue", "#B0E0E6"));
        colors.add(new ColorItem("Coral Blue", "#AFDCEC"));
        colors.add(new ColorItem("LightBlue", "#ADD8E6"));
        colors.add(new ColorItem("LightSteelBlue", "#B0CFDE"));
        colors.add(new ColorItem("Gulf Blue", "#C9DFEC"));
        colors.add(new ColorItem("Pastel Light Blue", "#D5D6EA"));
        colors.add(new ColorItem("Lavender Blue", "#E3E4FA"));
        colors.add(new ColorItem("White Blue", "#DBE9FA"));
        colors.add(new ColorItem("Lavender", "#E6E6FA"));
        colors.add(new ColorItem("Water", "#EBF4FA"));
        colors.add(new ColorItem("AliceBlue", "#F0F8FF"));
        colors.add(new ColorItem("GhostWhite", "#F8F8FF"));
        colors.add(new ColorItem("Azure", "#F0FFFF"));
        colors.add(new ColorItem("LightCyan", "#E0FFFF"));
        colors.add(new ColorItem("Light Slate", "#CCFFFF"));
        colors.add(new ColorItem("Electric Blue", "#9AFEFF"));
        colors.add(new ColorItem("Tron Blue", "#7DFDFE"));
        colors.add(new ColorItem("Blue Zircon", "#57FEFF"));
        colors.add(new ColorItem("Cyan or Aqua", "#00FFFF"));
        colors.add(new ColorItem("Bright Cyan", "#0AFFFF"));
        colors.add(new ColorItem("Celeste", "#50EBEC"));
        colors.add(new ColorItem("Blue Diamond", "#4EE2EC"));
        colors.add(new ColorItem("Bright Turquoise", "#16E2F5"));
        colors.add(new ColorItem("Blue Lagoon", "#8EEBEC"));
        colors.add(new ColorItem("PaleTurquoise", "#AFEEEE"));
        colors.add(new ColorItem("Pale Blue Lily", "#CFECEC"));
        colors.add(new ColorItem("Light Teal", "#B3D9D9"));
        colors.add(new ColorItem("Tiffany Blue", "#81D8D0"));
        colors.add(new ColorItem("Blue Hosta", "#77BFC7"));
        colors.add(new ColorItem("Cyan Opaque", "#92C7C7"));
        colors.add(new ColorItem("Northern Lights Blue", "#78C7C7"));
        colors.add(new ColorItem("Blue Green", "#7BCCB5"));
        colors.add(new ColorItem("MediumAquaMarine", "#66CDAA"));
        colors.add(new ColorItem("Aqua Seafoam Green", "#93E9BE"));
        colors.add(new ColorItem("Magic Mint", "#AAF0D1"));
        colors.add(new ColorItem("Light Aquamarine", "#93FFE8"));
        colors.add(new ColorItem("Aquamarine", "#7FFFD4"));
        colors.add(new ColorItem("Bright Teal", "#01F9C6"));
        colors.add(new ColorItem("Turquoise", "#40E0D0"));
        colors.add(new ColorItem("MediumTurquoise", "#48D1CC"));
        colors.add(new ColorItem("Deep Turquoise", "#48CCCD"));
        colors.add(new ColorItem("Jellyfish", "#46C7C7"));
        colors.add(new ColorItem("Blue Turquoise", "#43C6DB"));
        colors.add(new ColorItem("DarkTurquoise", "#00CED1"));
        colors.add(new ColorItem("Macaw Blue Green", "#43BFC7"));
        colors.add(new ColorItem("LightSeaGreen", "#20B2AA"));
        colors.add(new ColorItem("Seafoam Green", "#3EA99F"));
        colors.add(new ColorItem("CadetBlue", "#5F9EA0"));
        colors.add(new ColorItem("Deep Sea", "#3B9C9C"));
        colors.add(new ColorItem("Teal Green", "#00827F"));
        colors.add(new ColorItem("Teal", "#008080"));
        colors.add(new ColorItem("Teal Blue", "#007C80"));
        colors.add(new ColorItem("Medium Teal", "#045F5F"));
        colors.add(new ColorItem("Dark Teal", "#045D5D"));
        colors.add(new ColorItem("Deep Teal", "#033E3E"));
        colors.add(new ColorItem("DarkSlateGray or DarkSlateGrey", "#25383C"));
        colors.add(new ColorItem("Gunmetal", "#2C3539"));
        colors.add(new ColorItem("Blue Moss Green", "#3C565B"));
        colors.add(new ColorItem("Beetle Green", "#4C787E"));
        colors.add(new ColorItem("Grayish Turquoise", "#5E7D7E"));
        colors.add(new ColorItem("Greenish Blue", "#307D7E"));
        colors.add(new ColorItem("Aquamarine Stone", "#348781"));
        colors.add(new ColorItem("Sea Turtle Green", "#438D80"));
        colors.add(new ColorItem("Dull Sea Green", "#4E8975"));
        colors.add(new ColorItem("Dark Green Blue", "#1F6357"));
        colors.add(new ColorItem("Deep Sea Green", "#306754"));
        colors.add(new ColorItem("Bottle Green", "#006A4E"));
        colors.add(new ColorItem("SeaGreen", "#2E8B57"));
        colors.add(new ColorItem("Elf Green", "#1B8A6B"));
        colors.add(new ColorItem("Dark Mint", "#31906E"));
        colors.add(new ColorItem("Jade", "#00A36C"));
        colors.add(new ColorItem("Earth Green", "#34A56F"));
        colors.add(new ColorItem("Chrome Green", "#1AA260"));
        colors.add(new ColorItem("Mint", "#3EB489"));
        colors.add(new ColorItem("Emerald", "#50C878"));
        colors.add(new ColorItem("Isle Of Man Green", "#22CE83"));
        colors.add(new ColorItem("MediumSeaGreen", "#3CB371"));
        colors.add(new ColorItem("Metallic Green", "#7C9D8E"));
        colors.add(new ColorItem("Camouflage Green", "#78866B"));
        colors.add(new ColorItem("Sage Green", "#848B79"));
        colors.add(new ColorItem("Hazel Green", "#617C58"));
        colors.add(new ColorItem("Venom Green", "#728C00"));
        colors.add(new ColorItem("OliveDrab", "#6B8E23"));
        colors.add(new ColorItem("Olive", "#808000"));
        colors.add(new ColorItem("Ebony", "#555D50"));
        colors.add(new ColorItem("DarkOliveGreen", "#556B2F"));
        colors.add(new ColorItem("Military Green", "#4E5B31"));
        colors.add(new ColorItem("Green Leaves", "#3A5F0B"));
        colors.add(new ColorItem("Army Green", "#4B5320"));
        colors.add(new ColorItem("Fern Green", "#667C26"));
        colors.add(new ColorItem("Fall Forest Green", "#4E9258"));
        colors.add(new ColorItem("Irish Green", "#08A04B"));
        colors.add(new ColorItem("Pine Green", "#387C44"));
        colors.add(new ColorItem("Medium Forest Green", "#347235"));
        colors.add(new ColorItem("Racing Green", "#27742C"));
        colors.add(new ColorItem("Jungle Green", "#347C2C"));
        colors.add(new ColorItem("Cactus Green", "#227442"));
        colors.add(new ColorItem("ForestGreen", "#228B22"));
        colors.add(new ColorItem("Green", "#008000"));
        colors.add(new ColorItem("DarkGreen", "#006400"));
        colors.add(new ColorItem("Deep Green", "#056608"));
        colors.add(new ColorItem("Deep Emerald Green", "#046307"));
        colors.add(new ColorItem("Hunter Green", "#355E3B"));
        colors.add(new ColorItem("Dark Forest Green", "#254117"));
        colors.add(new ColorItem("Lotus Green", "#004225"));
        colors.add(new ColorItem("Broccoli Green", "#026C3D"));
        colors.add(new ColorItem("Seaweed Green", "#437C17"));
        colors.add(new ColorItem("Shamrock Green", "#347C17"));
        colors.add(new ColorItem("Green Onion", "#6AA121"));
        colors.add(new ColorItem("Moss Green", "#8A9A5B"));
        colors.add(new ColorItem("Grass Green", "#3F9B0B"));
        colors.add(new ColorItem("Green Pepper", "#4AA02C"));
        colors.add(new ColorItem("Dark Lime Green", "#41A317"));
        colors.add(new ColorItem("Parrot Green", "#12AD2B"));
        colors.add(new ColorItem("Clover Green", "#3EA055"));
        colors.add(new ColorItem("Dinosaur Green", "#73A16C"));
        colors.add(new ColorItem("Green Snake", "#6CBB3C"));
        colors.add(new ColorItem("Alien Green", "#6CC417"));
        colors.add(new ColorItem("Green Apple", "#4CC417"));
        colors.add(new ColorItem("LimeGreen", "#32CD32"));
        colors.add(new ColorItem("Pea Green", "#52D017"));
        colors.add(new ColorItem("Kelly Green", "#4CC552"));
        colors.add(new ColorItem("Zombie Green", "#54C571"));
        colors.add(new ColorItem("Green Peas", "#89C35C"));
        colors.add(new ColorItem("Dollar Bill Green", "#85BB65"));
        colors.add(new ColorItem("Frog Green", "#99C68E"));
        colors.add(new ColorItem("Turquoise Green", "#A0D6B4"));
        colors.add(new ColorItem("DarkSeaGreen", "#8FBC8F"));
        colors.add(new ColorItem("Basil Green", "#829F82"));
        colors.add(new ColorItem("Gray Green", "#A2AD9C"));
        colors.add(new ColorItem("Light Olive Green", "#B8BC86"));
        colors.add(new ColorItem("Iguana Green", "#9CB071"));
        colors.add(new ColorItem("Citron Green", "#8FB31D"));
        colors.add(new ColorItem("Acid Green", "#B0BF1A"));
        colors.add(new ColorItem("Avocado Green", "#B2C248"));
        colors.add(new ColorItem("Pistachio Green", "#9DC209"));
        colors.add(new ColorItem("Salad Green", "#A1C935"));
        colors.add(new ColorItem("YellowGreen", "#9ACD32"));
        colors.add(new ColorItem("Pastel Green", "#77DD77"));
        colors.add(new ColorItem("Hummingbird Green", "#7FE817"));
        colors.add(new ColorItem("Nebula Green", "#59E817"));
        colors.add(new ColorItem("Stoplight Go Green", "#57E964"));
        colors.add(new ColorItem("Neon Green", "#16F529"));
        colors.add(new ColorItem("Jade Green", "#5EFB6E"));
        colors.add(new ColorItem("SpringGreen", "#00FF7F"));
        colors.add(new ColorItem("Ocean Green", "#00FF80"));
        colors.add(new ColorItem("Lime Mint Green", "#36F57F"));
        colors.add(new ColorItem("MediumSpringGreen", "#00FA9A"));
        colors.add(new ColorItem("Aqua Green", "#12E193"));
        colors.add(new ColorItem("Emerald Green", "#5FFB17"));
        colors.add(new ColorItem("Lime", "#00FF00"));
        colors.add(new ColorItem("LawnGreen", "#7CFC00"));
        colors.add(new ColorItem("Bright Green", "#66FF00"));
        colors.add(new ColorItem("Chartreuse", "#7FFF00"));
        colors.add(new ColorItem("Yellow Lawn Green", "#87F717"));
        colors.add(new ColorItem("Aloe Vera Green", "#98F516"));
        colors.add(new ColorItem("Dull Green Yellow", "#B1FB17"));
        colors.add(new ColorItem("Lemon Green", "#ADF802"));
        colors.add(new ColorItem("GreenYellow", "#ADFF2F"));
        colors.add(new ColorItem("Chameleon Green", "#BDF516"));
        colors.add(new ColorItem("Neon Yellow Green", "#DAEE01"));
        colors.add(new ColorItem("Yellow Green Grosbeak", "#E2F516"));
        colors.add(new ColorItem("Tea Green", "#CCFB5D"));
        colors.add(new ColorItem("Slime Green", "#BCE954"));
        colors.add(new ColorItem("Algae Green", "#64E986"));
        colors.add(new ColorItem("LightGreen", "#90EE90"));
        colors.add(new ColorItem("Dragon Green", "#6AFB92"));
        colors.add(new ColorItem("PaleGreen", "#98FB98"));
        colors.add(new ColorItem("Mint Green", "#98FF98"));
        colors.add(new ColorItem("Green Thumb", "#B5EAAA"));
        colors.add(new ColorItem("Organic Brown", "#E3F9A6"));
        colors.add(new ColorItem("Light Jade", "#C3FDB8"));
        colors.add(new ColorItem("Light Mint Green", "#C2E5D3"));
        colors.add(new ColorItem("Light Rose Green", "#DBF9DB"));
        colors.add(new ColorItem("Chrome White", "#E8F1D4"));
        colors.add(new ColorItem("HoneyDew", "#F0FFF0"));
        colors.add(new ColorItem("MintCream", "#F5FFFA"));
        colors.add(new ColorItem("LemonChiffon", "#FFFACD"));
        colors.add(new ColorItem("Parchment", "#FFFFC2"));
        colors.add(new ColorItem("Cream", "#FFFFCC"));
        colors.add(new ColorItem("Cream White", "#FFFDD0"));
        colors.add(new ColorItem("LightGoldenRodYellow", "#FAFAD2"));
        colors.add(new ColorItem("LightYellow", "#FFFFE0"));
        colors.add(new ColorItem("Beige", "#F5F5DC"));
        colors.add(new ColorItem("White Yellow", "#F2F0DF"));
        colors.add(new ColorItem("Cornsilk", "#FFF8DC"));
        colors.add(new ColorItem("Blonde", "#FBF6D9"));
        colors.add(new ColorItem("AntiqueWhite", "#FAEBD7"));
        colors.add(new ColorItem("Light Beige", "#FFF0DB"));
        colors.add(new ColorItem("PapayaWhip", "#FFEFD5"));
        colors.add(new ColorItem("Champagne", "#F7E7CE"));
        colors.add(new ColorItem("BlanchedAlmond", "#FFEBCD"));
        colors.add(new ColorItem("Bisque", "#FFE4C4"));
        colors.add(new ColorItem("Wheat", "#F5DEB3"));
        colors.add(new ColorItem("Moccasin", "#FFE4B5"));
        colors.add(new ColorItem("Peach", "#FFE5B4"));
        colors.add(new ColorItem("Light Orange", "#FED8B1"));
        colors.add(new ColorItem("PeachPuff", "#FFDAB9"));
        colors.add(new ColorItem("Coral Peach", "#FBD5AB"));
        colors.add(new ColorItem("NavajoWhite", "#FFDEAD"));
        colors.add(new ColorItem("Golden Blonde", "#FBE7A1"));
        colors.add(new ColorItem("Golden Silk", "#F3E3C3"));
        colors.add(new ColorItem("Dark Blonde", "#F0E2B6"));
        colors.add(new ColorItem("Light Gold", "#F1E5AC"));
        colors.add(new ColorItem("Vanilla", "#F3E5AB"));
        colors.add(new ColorItem("Tan Brown", "#ECE5B6"));
        colors.add(new ColorItem("Dirty White", "#E8E4C9"));
        colors.add(new ColorItem("PaleGoldenRod", "#EEE8AA"));
        colors.add(new ColorItem("Khaki", "#F0E68C"));
        colors.add(new ColorItem("Cardboard Brown", "#EDDA74"));
        colors.add(new ColorItem("Harvest Gold", "#EDE275"));
        colors.add(new ColorItem("Sun Yellow", "#FFE87C"));
        colors.add(new ColorItem("Corn Yellow", "#FFF380"));
        colors.add(new ColorItem("Pastel Yellow", "#FAF884"));
        colors.add(new ColorItem("Neon Yellow", "#FFFF33"));
        colors.add(new ColorItem("Yellow", "#FFFF00"));
        colors.add(new ColorItem("Lemon Yellow", "#FEF250"));
        colors.add(new ColorItem("Canary Yellow", "#FFEF00"));
        colors.add(new ColorItem("Banana Yellow", "#F5E216"));
        colors.add(new ColorItem("Mustard Yellow", "#FFDB58"));
        colors.add(new ColorItem("Golden Yellow", "#FFDF00"));
        colors.add(new ColorItem("Bold Yellow", "#F9DB24"));
        colors.add(new ColorItem("Safety Yellow", "#EED202"));
        colors.add(new ColorItem("Rubber Ducky Yellow", "#FFD801"));
        colors.add(new ColorItem("Gold", "#FFD700"));
        colors.add(new ColorItem("Bright Gold", "#FDD017"));
        colors.add(new ColorItem("Chrome Gold", "#FFCE44"));
        colors.add(new ColorItem("Golden Brown", "#EAC117"));
        colors.add(new ColorItem("Deep Yellow", "#F6BE00"));
        colors.add(new ColorItem("Macaroni and Cheese", "#F2BB66"));
        colors.add(new ColorItem("Amber", "#FFBF00"));
        colors.add(new ColorItem("Saffron", "#FBB917"));
        colors.add(new ColorItem("Neon Gold", "#FDBD01"));
        colors.add(new ColorItem("Beer", "#FBB117"));
        colors.add(new ColorItem("Yellow Orange or Orange Yellow", "#FFAE42"));
        colors.add(new ColorItem("Cantaloupe", "#FFA62F"));
        colors.add(new ColorItem("Cheese Orange", "#FFA600"));
        colors.add(new ColorItem("Orange", "#FFA500"));
        colors.add(new ColorItem("Brown Sand", "#EE9A4D"));
        colors.add(new ColorItem("SandyBrown", "#F4A460"));
        colors.add(new ColorItem("Brown Sugar", "#E2A76F"));
        colors.add(new ColorItem("Camel Brown", "#C19A6B"));
        colors.add(new ColorItem("Deer Brown", "#E6BF83"));
        colors.add(new ColorItem("BurlyWood", "#DEB887"));
        colors.add(new ColorItem("Tan", "#D2B48C"));
        colors.add(new ColorItem("Light French Beige", "#C8AD7F"));
        colors.add(new ColorItem("Sand", "#C2B280"));
        colors.add(new ColorItem("Soft Hazel", "#C6BA8B"));
        colors.add(new ColorItem("Sage", "#BCB88A"));
        colors.add(new ColorItem("Fall Leaf Brown", "#C8B560"));
        colors.add(new ColorItem("Ginger Brown", "#C9BE62"));
        colors.add(new ColorItem("Bronze Gold", "#C9AE5D"));
        colors.add(new ColorItem("DarkKhaki", "#BDB76B"));
        colors.add(new ColorItem("Olive Green", "#BAB86C"));
        colors.add(new ColorItem("Brass", "#B5A642"));
        colors.add(new ColorItem("Cookie Brown", "#C7A317"));
        colors.add(new ColorItem("Metallic Gold", "#D4AF37"));
        colors.add(new ColorItem("Mustard", "#E1AD01"));
        colors.add(new ColorItem("Bee Yellow", "#E9AB17"));
        colors.add(new ColorItem("Marigold", "#EBA832"));
        colors.add(new ColorItem("School Bus Yellow", "#E8A317"));
        colors.add(new ColorItem("GoldenRod", "#DAA520"));
        colors.add(new ColorItem("Orange Gold", "#D4A017"));
        colors.add(new ColorItem("Champagne Gold", "#D29F51"));
        colors.add(new ColorItem("Caramel", "#C68E17"));
        colors.add(new ColorItem("DarkGoldenRod", "#B8860B"));
        colors.add(new ColorItem("Cinnamon", "#C58917"));
        colors.add(new ColorItem("Peru", "#CD853F"));
        colors.add(new ColorItem("Bronze", "#CD7F32"));
        colors.add(new ColorItem("Pumpkin Pie", "#CA762B"));
        colors.add(new ColorItem("Tiger Orange", "#C88141"));
        colors.add(new ColorItem("Copper", "#B87333"));
        colors.add(new ColorItem("Dark Gold", "#AA6C39"));
        colors.add(new ColorItem("Metallic Bronze", "#A97142"));
        colors.add(new ColorItem("Dark Almond", "#AB784E"));
        colors.add(new ColorItem("Wood", "#966F33"));
        colors.add(new ColorItem("Khaki Brown", "#906E3E"));
        colors.add(new ColorItem("Oak Brown", "#806517"));
        colors.add(new ColorItem("Antique Bronze", "#665D1E"));
        colors.add(new ColorItem("Hazel", "#8E7618"));
        colors.add(new ColorItem("Dark Yellow", "#8B8000"));
        colors.add(new ColorItem("Dark Moccasin", "#827839"));
        colors.add(new ColorItem("Khaki Green", "#8A865D"));
        colors.add(new ColorItem("Millennium Jade", "#93917C"));
        colors.add(new ColorItem("Dark Beige", "#9F8C76"));
        colors.add(new ColorItem("Bullet Shell", "#AF9B60"));
        colors.add(new ColorItem("Army Brown", "#827B60"));
        colors.add(new ColorItem("Sandstone", "#786D5F"));
        colors.add(new ColorItem("Taupe", "#483C32"));
        colors.add(new ColorItem("Dark Grayish Olive", "#4A412A"));
        colors.add(new ColorItem("Dark Hazel Brown", "#473810"));
        colors.add(new ColorItem("Mocha", "#493D26"));
        colors.add(new ColorItem("Milk Chocolate", "#513B1C"));
        colors.add(new ColorItem("Gray Brown", "#3D3635"));
        colors.add(new ColorItem("Dark Coffee", "#3B2F2F"));
        colors.add(new ColorItem("Western Charcoal", "#49413F"));
        colors.add(new ColorItem("Old Burgundy", "#43302E"));
        colors.add(new ColorItem("Red Brown", "#622F22"));
        colors.add(new ColorItem("Bakers Brown", "#5C3317"));
        colors.add(new ColorItem("Pullman Brown", "#644117"));
        colors.add(new ColorItem("Dark Brown", "#654321"));
        colors.add(new ColorItem("Sepia Brown", "#704214"));
        colors.add(new ColorItem("Dark Bronze", "#804A00"));
        colors.add(new ColorItem("Coffee", "#6F4E37"));
        colors.add(new ColorItem("Brown Bear", "#835C3B"));
        colors.add(new ColorItem("Red Dirt", "#7F5217"));
        colors.add(new ColorItem("Sepia", "#7F462C"));
        colors.add(new ColorItem("Sienna", "#A0522D"));
        colors.add(new ColorItem("SaddleBrown", "#8B4513"));
        colors.add(new ColorItem("Dark Sienna", "#8A4117"));
        colors.add(new ColorItem("Sangria", "#7E3817"));
        colors.add(new ColorItem("Blood Red", "#7E3517"));
        colors.add(new ColorItem("Chestnut", "#954535"));
        colors.add(new ColorItem("Coral Brown", "#9E4638"));
        colors.add(new ColorItem("Deep Amber", "#A05544"));
        colors.add(new ColorItem("Chestnut Red", "#C34A2C"));
        colors.add(new ColorItem("Ginger Red", "#B83C08"));
        colors.add(new ColorItem("Mahogany", "#C04000"));
        colors.add(new ColorItem("Red Gold", "#EB5406"));
        colors.add(new ColorItem("Red Fox", "#C35817"));
        colors.add(new ColorItem("Ginger", "#B06500"));
        colors.add(new ColorItem("Dark Bisque", "#B86500"));
        colors.add(new ColorItem("Light Brown", "#B5651D"));
        colors.add(new ColorItem("Petra Gold", "#B76734"));
        colors.add(new ColorItem("Brown Rust", "#A55D35"));
        colors.add(new ColorItem("Rust", "#C36241"));
        colors.add(new ColorItem("Copper Red", "#CB6D51"));
        colors.add(new ColorItem("Orange Salmon", "#C47451"));
        colors.add(new ColorItem("Chocolate", "#D2691E"));
        colors.add(new ColorItem("Sedona", "#CC6600"));
        colors.add(new ColorItem("Papaya Orange", "#E56717"));
        colors.add(new ColorItem("Halloween Orange", "#E66C2C"));
        colors.add(new ColorItem("Neon Orange", "#FF6700"));
        colors.add(new ColorItem("Bright Orange", "#FF5F1F"));
        colors.add(new ColorItem("Fluro Orange", "#FE632A"));
        colors.add(new ColorItem("Pumpkin Orange", "#F87217"));
        colors.add(new ColorItem("Safety Orange", "#FF7900"));
        colors.add(new ColorItem("Carrot Orange", "#F88017"));
        colors.add(new ColorItem("DarkOrange", "#FF8C00"));
        colors.add(new ColorItem("Construction Cone Orange", "#F87431"));
        colors.add(new ColorItem("Indian Saffron", "#FF7722"));
        colors.add(new ColorItem("Sunrise Orange", "#E67451"));
        colors.add(new ColorItem("Mango Orange", "#FF8040"));
        colors.add(new ColorItem("Coral", "#FF7F50"));
        colors.add(new ColorItem("Basket Ball Orange", "#F88158"));
        colors.add(new ColorItem("Light Salmon Rose", "#F9966B"));
        colors.add(new ColorItem("LightSalmon", "#FFA07A"));
        colors.add(new ColorItem("Pink Orange", "#F89880"));
        colors.add(new ColorItem("DarkSalmon", "#E9967A"));
        colors.add(new ColorItem("Tangerine", "#E78A61"));
        colors.add(new ColorItem("Light Copper", "#DA8A67"));
        colors.add(new ColorItem("Salmon Pink", "#FF8674"));
        colors.add(new ColorItem("Salmon", "#FA8072"));
        colors.add(new ColorItem("Peach Pink", "#F98B88"));
        colors.add(new ColorItem("LightCoral", "#F08080"));
        colors.add(new ColorItem("Pastel Red", "#F67280"));
        colors.add(new ColorItem("Pink Coral", "#E77471"));
        colors.add(new ColorItem("Bean Red", "#F75D59"));
        colors.add(new ColorItem("Valentine Red", "#E55451"));
        colors.add(new ColorItem("IndianRed", "#CD5C5C"));
        colors.add(new ColorItem("Tomato", "#FF6347"));
        colors.add(new ColorItem("Shocking Orange", "#E55B3C"));
        colors.add(new ColorItem("OrangeRed", "#FF4500"));
        colors.add(new ColorItem("Red", "#FF0000"));
        colors.add(new ColorItem("Neon Red", "#FD1C03"));
        colors.add(new ColorItem("Scarlet Red", "#FF2400"));
        colors.add(new ColorItem("Ruby Red", "#F62217"));
        colors.add(new ColorItem("Ferrari Red", "#F70D1A"));
        colors.add(new ColorItem("Fire Engine Red", "#F62817"));
        colors.add(new ColorItem("Lava Red", "#E42217"));
        colors.add(new ColorItem("Love Red", "#E41B17"));
        colors.add(new ColorItem("Grapefruit", "#DC381F"));
        colors.add(new ColorItem("Strawberry Red", "#C83F49"));
        colors.add(new ColorItem("Cherry Red", "#C24641"));
        colors.add(new ColorItem("Chilli Pepper", "#C11B17"));
        colors.add(new ColorItem("FireBrick", "#B22222"));
        colors.add(new ColorItem("Tomato Sauce Red", "#B21807"));
        colors.add(new ColorItem("Brown", "#A52A2A"));
        colors.add(new ColorItem("Carbon Red", "#A70D2A"));
        colors.add(new ColorItem("Cranberry", "#9F000F"));
        colors.add(new ColorItem("Saffron Red", "#931314"));
        colors.add(new ColorItem("Crimson Red", "#990000"));
        colors.add(new ColorItem("Red Wine or Wine Red", "#990012"));
        colors.add(new ColorItem("DarkRed", "#8B0000"));
        colors.add(new ColorItem("Maroon Red", "#8F0B0B"));
        colors.add(new ColorItem("Maroon", "#800000"));
        colors.add(new ColorItem("Burgundy", "#8C001A"));
        colors.add(new ColorItem("Vermilion", "#7E191B"));
        colors.add(new ColorItem("Deep Red", "#800517"));
        colors.add(new ColorItem("Dark Burgundy", "#800020"));
        colors.add(new ColorItem("Garnet Red", "#733635"));
        colors.add(new ColorItem("Red Blood", "#660000"));
        colors.add(new ColorItem("Blood Night", "#551606"));
        colors.add(new ColorItem("Dark Scarlet", "#560319"));
        colors.add(new ColorItem("Chocolate Brown", "#3F000F"));
        colors.add(new ColorItem("Black Bean", "#3D0C02"));
        colors.add(new ColorItem("Dark Maroon", "#2F0909"));
        colors.add(new ColorItem("Midnight", "#2B1B17"));
        colors.add(new ColorItem("Purple Lily", "#550A35"));
        colors.add(new ColorItem("Purple Maroon", "#810541"));
        colors.add(new ColorItem("Plum Pie", "#7D0541"));
        colors.add(new ColorItem("Plum Velvet", "#7D0552"));
        colors.add(new ColorItem("Dark Raspberry", "#872657"));
        colors.add(new ColorItem("Velvet Maroon", "#7E354D"));
        colors.add(new ColorItem("Rosy-Finch", "#7F4E52"));
        colors.add(new ColorItem("Dull Purple", "#7F525D"));
        colors.add(new ColorItem("Puce", "#7F5A58"));
        colors.add(new ColorItem("Rose Dust", "#997070"));
        colors.add(new ColorItem("Pastel Brown", "#B1907F"));
        colors.add(new ColorItem("Rosy Pink", "#B38481"));
        colors.add(new ColorItem("RosyBrown", "#BC8F8F"));
        colors.add(new ColorItem("Khaki Rose", "#C5908E"));
        colors.add(new ColorItem("Lipstick Pink", "#C48793"));
        colors.add(new ColorItem("Dusky Pink", "#CC7A8B"));
        colors.add(new ColorItem("Pink Brown", "#C48189"));
        colors.add(new ColorItem("Old Rose", "#C08081"));
        colors.add(new ColorItem("Dusty Pink", "#D58A94"));
        colors.add(new ColorItem("Pink Daisy", "#E799A3"));
        colors.add(new ColorItem("Rose", "#E8ADAA"));
        colors.add(new ColorItem("Dusty Rose", "#C9A9A6"));
        colors.add(new ColorItem("Silver Pink", "#C4AEAD"));
        colors.add(new ColorItem("Gold Pink", "#E6C7C2"));
        colors.add(new ColorItem("Rose Gold", "#ECC5C0"));
        colors.add(new ColorItem("Deep Peach", "#FFCBA4"));
        colors.add(new ColorItem("Pastel Orange", "#F8B88B"));
        colors.add(new ColorItem("Desert Sand", "#EDC9AF"));
        colors.add(new ColorItem("Unbleached Silk", "#FFDDCA"));
        colors.add(new ColorItem("Pig Pink", "#FDD7E4"));
        colors.add(new ColorItem("Pale Pink", "#F2D4D7"));
        colors.add(new ColorItem("Blush", "#FFE6E8"));
        colors.add(new ColorItem("MistyRose", "#FFE4E1"));
        colors.add(new ColorItem("Pink Bubble Gum", "#FFDFDD"));
        colors.add(new ColorItem("Light Rose", "#FBCFCD"));
        colors.add(new ColorItem("Light Red", "#FFCCCB"));
        colors.add(new ColorItem("Rose Quartz", "#F7CAC9"));
        colors.add(new ColorItem("Warm Pink", "#F6C6BD"));
        colors.add(new ColorItem("Deep Rose", "#FBBBB9"));
        colors.add(new ColorItem("Pink", "#FFC0CB"));
        colors.add(new ColorItem("LightPink", "#FFB6C1"));
        colors.add(new ColorItem("Soft Pink", "#FFB8BF"));
        colors.add(new ColorItem("Powder Pink", "#FFB2D0"));
        colors.add(new ColorItem("Donut Pink", "#FAAFBE"));
        colors.add(new ColorItem("Baby Pink", "#FAAFBA"));
        colors.add(new ColorItem("Flamingo Pink", "#F9A7B0"));
        colors.add(new ColorItem("Pastel Pink", "#FEA3AA"));
        colors.add(new ColorItem("Rose Pink or Pink Rose", "#E7A1B0"));
        colors.add(new ColorItem("Cadillac Pink", "#E38AAE"));
        colors.add(new ColorItem("Carnation Pink", "#F778A1"));
        colors.add(new ColorItem("Pastel Rose", "#E5788F"));
        colors.add(new ColorItem("Blush Red", "#E56E94"));
        colors.add(new ColorItem("PaleVioletRed", "#DB7093"));
        colors.add(new ColorItem("Purple Pink", "#D16587"));
        colors.add(new ColorItem("Tulip Pink", "#C25A7C"));
        colors.add(new ColorItem("Bashful Pink", "#C25283"));
        colors.add(new ColorItem("Dark Pink", "#E75480"));
        colors.add(new ColorItem("Dark Hot Pink", "#F660AB"));
        colors.add(new ColorItem("HotPink", "#FF69B4"));
        colors.add(new ColorItem("Watermelon Pink", "#FC6C85"));
        colors.add(new ColorItem("Violet Red", "#F6358A"));
        colors.add(new ColorItem("Hot Deep Pink", "#F52887"));
        colors.add(new ColorItem("Bright Pink", "#FF007F"));
        colors.add(new ColorItem("Red Magenta", "#FF0080"));
        colors.add(new ColorItem("DeepPink", "#FF1493"));
        colors.add(new ColorItem("Neon Pink", "#F535AA"));
        colors.add(new ColorItem("Chrome Pink", "#FF33AA"));
        colors.add(new ColorItem("Neon Hot Pink", "#FD349C"));
        colors.add(new ColorItem("Pink Cupcake", "#E45E9D"));
        colors.add(new ColorItem("Royal Pink", "#E759AC"));
        colors.add(new ColorItem("Dimorphotheca Magenta", "#E3319D"));
        colors.add(new ColorItem("Barbie Pink", "#DA1884"));
        colors.add(new ColorItem("Pink Lemonade", "#E4287C"));
        colors.add(new ColorItem("Red Pink", "#FA2A55"));
        colors.add(new ColorItem("Raspberry", "#E30B5D"));
        colors.add(new ColorItem("Crimson", "#DC143C"));
        colors.add(new ColorItem("Bright Maroon", "#C32148"));
        colors.add(new ColorItem("Rose Red", "#C21E56"));
        colors.add(new ColorItem("Rogue Pink", "#C12869"));
        colors.add(new ColorItem("Burnt Pink", "#C12267"));
        colors.add(new ColorItem("Pink Violet", "#CA226B"));
        colors.add(new ColorItem("Magenta Pink", "#CC338B"));
        colors.add(new ColorItem("MediumVioletRed", "#C71585"));
        colors.add(new ColorItem("Dark Carnation Pink", "#C12283"));
        colors.add(new ColorItem("Light Maroon", "#A24857"));
        colors.add(new ColorItem("Raspberry Purple", "#B3446C"));
        colors.add(new ColorItem("Pink Plum", "#B93B8F"));
        colors.add(new ColorItem("Orchid", "#DA70D6"));
        colors.add(new ColorItem("Deep Mauve", "#DF73D4"));
        colors.add(new ColorItem("Violet", "#EE82EE"));
        colors.add(new ColorItem("Fuchsia Pink", "#FF77FF"));
        colors.add(new ColorItem("Bright Neon Pink", "#F433FF"));
        colors.add(new ColorItem("Magenta or Fuchsia", "#FF00FF"));
        colors.add(new ColorItem("Crimson Purple", "#E238EC"));
        colors.add(new ColorItem("Heliotrope Purple", "#D462FF"));
        colors.add(new ColorItem("Tyrian Purple", "#C45AEC"));
        colors.add(new ColorItem("MediumOrchid", "#BA55D3"));
        colors.add(new ColorItem("Purple Flower", "#A74AC7"));
        colors.add(new ColorItem("Orchid Purple", "#B048B5"));
        colors.add(new ColorItem("Rich Lilac", "#B666D2"));
        colors.add(new ColorItem("Pastel Violet", "#D291BC"));
        colors.add(new ColorItem("Rosy", "#A17188"));
        colors.add(new ColorItem("Mauve Taupe", "#915F6D"));
        colors.add(new ColorItem("Viola Purple", "#7E587E"));
        colors.add(new ColorItem("Eggplant", "#614051"));
        colors.add(new ColorItem("Plum Purple", "#583759"));
        colors.add(new ColorItem("Grape", "#5E5A80"));
        colors.add(new ColorItem("Purple Navy", "#4E5180"));
        colors.add(new ColorItem("SlateBlue", "#6A5ACD"));
        colors.add(new ColorItem("Blue Lotus", "#6960EC"));
        colors.add(new ColorItem("Blurple", "#5865F2"));
        colors.add(new ColorItem("Light Slate Blue", "#736AFF"));
        colors.add(new ColorItem("MediumSlateBlue", "#7B68EE"));
        colors.add(new ColorItem("Periwinkle Purple", "#7575CF"));
        colors.add(new ColorItem("Very Peri", "#6667AB"));
        colors.add(new ColorItem("Dark Lavender", "#734F96"));
        colors.add(new ColorItem("Bright Grape", "#6F2DA8"));
        colors.add(new ColorItem("Bright Purple", "#6A0DAD"));
        colors.add(new ColorItem("Purple Amethyst", "#6C2DC7"));
        colors.add(new ColorItem("Blue Magenta", "#822EFF"));
        colors.add(new ColorItem("Dark Blurple", "#5539CC"));
        colors.add(new ColorItem("Deep Periwinkle", "#5453A6"));
        colors.add(new ColorItem("DarkSlateBlue", "#483D8B"));
        colors.add(new ColorItem("Purple Haze", "#4E387E"));
        colors.add(new ColorItem("Purple Iris", "#571B7E"));
        colors.add(new ColorItem("Dark Purple", "#4B0150"));
        colors.add(new ColorItem("Deep Purple", "#36013F"));
        colors.add(new ColorItem("Midnight Purple", "#2E1A47"));
        colors.add(new ColorItem("Purple Monster", "#461B7E"));
        colors.add(new ColorItem("Indigo", "#4B0082"));
        colors.add(new ColorItem("Blue Whale", "#342D7E"));
        colors.add(new ColorItem("RebeccaPurple", "#663399"));
        colors.add(new ColorItem("Purple Jam", "#6A287E"));
        colors.add(new ColorItem("DarkMagenta", "#8B008B"));
        colors.add(new ColorItem("Purple", "#800080"));
        colors.add(new ColorItem("French Lilac", "#86608E"));
        colors.add(new ColorItem("DarkOrchid", "#9932CC"));
        colors.add(new ColorItem("DarkViolet", "#9400D3"));
        colors.add(new ColorItem("Purple Violet", "#8D38C9"));
        colors.add(new ColorItem("MediumPurple", "#9370DB"));
        colors.add(new ColorItem("Amethyst", "#9966CC"));
        colors.add(new ColorItem("Lavender Purple", "#967BB6"));
        colors.add(new ColorItem("Pastel Purple", "#B39EB5"));
        colors.add(new ColorItem("Lavender", "#E6E6FA"));
        colors.add(new ColorItem("Thistle", "#D8BFD8"));
        colors.add(new ColorItem("Orchid", "#DA70D6"));
        colors.add(new ColorItem("Violet", "#EE82EE"));
        colors.add(new ColorItem("Plum", "#DDA0DD"));
        colors.add(new ColorItem("Mauve", "#E0B0FF"));
        colors.add(new ColorItem("Heliotrope", "#DF73FF"));
        colors.add(new ColorItem("Lavender Mist", "#E6E6FA"));
        colors.add(new ColorItem("Pale Lavender", "#F3E6FA"));
        colors.add(new ColorItem("Purple White", "#FAF0FF"));
        colors.add(new ColorItem("Ivory", "#FFFFF0"));
        colors.add(new ColorItem("Floral White", "#FFFAF0"));
        colors.add(new ColorItem("Seashell", "#FFF5EE"));
        colors.add(new ColorItem("Snow", "#FFFAFA"));
        colors.add(new ColorItem("White Smoke", "#F5F5F5"));
        colors.add(new ColorItem("Gainsboro", "#DCDCDC"));
        colors.add(new ColorItem("Light Gray", "#D3D3D3"));
        colors.add(new ColorItem("Silver", "#C0C0C0"));
        colors.add(new ColorItem("Dark Gray", "#A9A9A9"));
        colors.add(new ColorItem("Gray", "#808080"));
        colors.add(new ColorItem("Dim Gray", "#696969"));
        colors.add(new ColorItem("Light Slate Gray", "#778899"));
        colors.add(new ColorItem("Slate Gray", "#708090"));
        colors.add(new ColorItem("Dark Slate Gray", "#2F4F4F"));
        colors.add(new ColorItem("White", "#FFFFFF"));
        
        return colors;
    }
}
